lancms2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from event.views import EventListView, EventDetailView
from event.views import OrganizationDetailView, OrganizationCreateView

from core.views import UserDetailView

from event.views import organization_add_manager, organization_remove_manager

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'accounts/', include('allauth.urls')),
    url(r'accounts/profile/$', UserDetailView.as_view(), name='user_profile'),

    url(r'^$', EventListView.as_view(), name='event_list'),

    url(r'^o/(?P<slug>[\w-]+)/$', OrganizationDetailView.as_view(), name='org_detail'),
    url(r'^o/(?P<slug>[\w-]+)/addmanager/$', organization_add_manager, name='org_add_manager'),
    url(r'^o/(?P<slug>[\w-]+)/removemanager/(?P<user>\d+)/$', organization_remove_manager, name='org_remove_manager'),

    url(r'^e/(?P<slug>[\w-]+)/$', EventDetailView.as_view(), name='event_detail'),

    url(r'^a/org/create/$', OrganizationCreateView.as_view(), name='org_create'),
]

event/models.py
from django.db import models

from simple_history.models import HistoricalRecords
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from guardian.models import UserObjectPermission
from django.contrib.contenttypes.models import ContentType

class ActiveOrganizationManager(models.Manager):
    def get_queryset(self):
        return super(ActiveOrganizationManager, self).get_queryset().filter(is_active=True)

class ActiveEventManager(models.Manager):
    def get_queryset(self):
        return super(ActiveEventManager, self).get_queryset().filter(is_active=True,organization__is_active=True)

class Organization(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField()

    is_active = models.BooleanField(default=True)

    history = HistoricalRecords()

    # order is important for Managers
    # default (used in CBVs ie. is the first Manager)
    # admin uses default, unless specified in ModelAdmin
    objects = ActiveOrganizationManager()
    objects_admin = models.Manager()


    def get_absolute_url(self):
        return reverse('org_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


    def get_managers(self):
        codename='manage_organization'
        type = ContentType.objects.get_for_model(self)
        return UserObjectPermission.objects.filter(permission__codename=codename, object_pk=self.pk, content_type=type)

    class Meta:
            permissions = (
                ('manage_organization', 'Can manage organization'),
            )



class Event(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField()

    is_active = models.BooleanField(default=True)

    start = models.DateTimeField()
    end = models.DateTimeField()

    venuename = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    postalcode = models.CharField(max_length=10)
    city = models.CharField(max_length=64)
    country = models.CharField(max_length=256)

    organization = models.ForeignKey(Organization)

    history = HistoricalRecords()

    # order is important for Managers
    # default (used in CBVs ie. is the first Manager)
    # admin uses default, unless specified in ModelAdmin
    objects = ActiveEventManager()
    objects_admin = models.Manager()

    def __str__(self):
        return self.name


    def get_managers(self):
        codename='manage_event'
        type = ContentType.objects.get_for_model(self)
        return UserObjectPermission.objects.filter(permission__codename=codename, object_pk=self.pk, content_type=type)


    class Meta:
            permissions = (
                ('manage_event', 'Can manage event'),
            )

event/forms.py
# -*- coding: utf-8 -*-

from django import forms

from django.contrib.auth.models import User

from guardian.shortcuts import assign_perm, remove_perm

class AddManagerForm(forms.Form):
    username = forms.CharField(max_length=256)

    def user_exists(self):
        try:
            user = User.objects.get(username=self.cleaned_data['username'])
            return True
        except:
            return False

    def save(self, object, permission):
        user = User.objects.get(username=self.cleaned_data['username'])
        return assign_perm(permission, user, object)


class RemoveManagerForm(forms.Form):
    pass

    def save(self, object, user, permission):
        return remove_perm(permission, user, object)

event/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator

from django.core.exceptions import PermissionDenied

from django.contrib import messages

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from django.contrib.auth.models import User
from event.models import Event, Organization
from event.forms import AddManagerForm, RemoveManagerForm

class EventListView(ListView):
    model = Event

class EventDetailView(DetailView):
    model = Event

class OrganizationDetailView(DetailView):
    model = Organization


class OrganizationCreateView(CreateView):
    model = Organization
    fields = ['name', 'slug' ]

    @method_decorator(permission_required('event.add_organization', raise_exception=True))
    def dispatch(self, *args, **kwargs):
            return super(OrganizationCreateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(OrganizationCreateView, self).get_context_data(**kwargs)
        context['page_header'] = _('Create organization')
        return context


def organization_add_manager(request, slug):
    organization = get_object_or_404(Organization, slug=slug)

    if not request.user.has_perm('manage_organization', organization) and not request.user.has_perm('event.add_organization'):
        raise PermissionDenied

    c = {}
    c['organization'] = organization
    form = AddManagerForm()

    if request.method == 'POST':
        form = AddManagerForm(request.POST)
        if form.is_valid():
            if form.user_exists():
                form.save(organization, 'manage_organization')
                messages.add_message(request, messages.SUCCESS, _("User granted manager permissions")) 
                # FIXME: Should show a different message if user already
                # has manager rights. -- mboehn
                return redirect(organization)
            else:
                messages.add_message(request, messages.ERROR, _("User doesn't exist")) 

    c['form'] = form
    return render(request, 'event/organization_add_manager.html', c)


def organization_remove_manager(request, slug, user):
    organization = get_object_or_404(Organization, slug=slug)
    removeuser = get_object_or_404(User, pk=user)

    if not request.user.has_perm('manage_organization', organization) and not request.user.has_perm('event.add_organization'):
        raise PermissionDenied

    if request.user == removeuser:
        raise PermissionDenied

    c = {}
    c['organization'] = organization
    c['removeuser'] = removeuser

    form = RemoveManagerForm()

    if request.method == 'POST':
        form.save(organization, removeuser, 'manage_organization')
        messages.add_message(request, messages.SUCCESS, _("Removed user's manager permissions"))
        
        # if error:
        #messages.add_message(request, messages.ERROR, _("Something went wrong"))
        # FIXME: organization_remove_manager may need some more error checking or output
        return redirect(organization)

    c['form'] = form
    return render(request, 'event/organization_remove_manager.html', c)

templates/event/event_detail.html
{% extends "core/base.html"%}
{% load i18n %}

{% block content %}
<div class="container">

    <h1 class="page-header">{{event.name}} <small>{% trans "Event" %}</small></h1>

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans "When" %}</div>
                <div class="panel-body">
                    <ul>
                        <li>{% trans "Start:" %} {{event.start}}</li>
                        <li>{% trans "End:" %} {{event.end}}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans "Where" %}</div>
                <div class="panel-body">
                    <address>
                        <strong>{{event.venuename}}</strong><br>
                        {{event.address}}<br>
                        {{event.postalcode}} {{event.city}}<br>
                        {{event.country}}<br>
                    </address>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans "Organized by" %}</div>
                <div class="panel-body">
                        <a href="{% url 'org_detail' slug=event.organization.slug %}">{{event.organization.name}}</a>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

templates/event/event_list.html
{% extends "core/base.html"%}
{% load i18n %}

{% block content %}

<div class="container">

{% for event in object_list %}
<div class="list-group">
    <a href="{% url 'event_detail' slug=event.slug %}" class="list-group-item">
        <h3 class="list-group-item-heading">{{event.name}}</h3>
        <p class="list-group-item-text">{% if event.venuename %}<strong>{{event.venuename}}</strong>, {% endif %}{{event.city}}</p>
        <p class="list-group-item-text">{% trans "Organized by:" %} {{event.organization.name}}</p>
        <p class="list-group-item-text">{% trans "Start time:" %} {{event.start}}</p>
        <p class="list-group-item-text">{% trans "End time:" %} {{event.end}}</p>
    </a>

</div>
{% empty %}
<p>{% trans "No active events at this time" %}</p>
{% endfor %}

</div>

{% endblock %}

templates/event/organization_add_manager.html
{% extends "core/base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<div class="container">

<h1 class="page-header">{% trans "Add manager for" %} {{organization}}</h1>

<form class="form" method="post">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons submit="Submit"  %}
    {% endbuttons %}

</form>

</div>

{% endblock %}

templates/event/organization_detail.html
{% extends "core/base.html"%}
{% load i18n %}
{% load bootstrap3 %}
{% load account %}

{% load guardian_tags %}

{% block content %}

{% get_obj_perms request.user for organization as "org_perms" %}

<div class="container">

<h1 class="page-header">{{organization.name}} <small>{% trans "Organization" %}</small></h1>

<h2>About</h2>
<p> FIXME </p>

<h2>{% trans "Events" %}</h2>
{% for event in organization.event_set.all %}
<div class="list-group">
    <a href="{% url 'event_detail' slug=event.slug %}" class="list-group-item">
        <h3 class="list-group-item-heading">{{event.name}}</h3>
        <p class="list-group-item-text">{% trans "Organized by:" %} {{event.organization.name}}</p>
        <p class="list-group-item-text">{% trans "Start time:" %} {{event.start}}</p>
        <p class="list-group-item-text">{% trans "End time:" %} {{event.end}}</p>
    </a>
</div>
{% empty %}
<p>{% trans "This organization has no events" %}</p>
{% endfor %}

{% if "manage_organization" in org_perms or perms.event.add_organization %}
    <h2>{% trans "Management" %}</h2>
    <div class="well">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% trans "Managers" %}
                    <a href="{% url 'org_add_manager' slug=organization.slug %}"><span class="pull-right">{% bootstrap_icon "plus" %}</span></a>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped">
                    {% for managerinstance in organization.get_managers %}
                        <tr>
                            <td>
                            {% if managerinstance.user != request.user %}
                                <a href="{% url 'org_remove_manager' slug=organization.slug user=managerinstance.user.pk %}">{% bootstrap_icon "minus" %}</a>
                            {% endif %}
                            </td>
                            <td>{% user_display managerinstance.user %}</td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {% trans "Events" %}
                    <a href="#"><span class="pull-right">{% bootstrap_icon "plus" %}</span></a>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped">
                        <tr>
                            {% for event in organization.event_set.all %}
                            <td>{{event.name}}</td>
                            {% endfor %}
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans "About" %}</div>
                <div class="panel-body">
                </div>
            </div>
        </div>
    </div>
    </div>
{% endif %}

</div>

{% endblock %}

templates/event/organization_form.html
{% extends "core/base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<div class="container">

<h1 class="page-header">{{page_header|default:"Organization"}}</h1>

<form class="form" method="post">
    {% csrf_token %}

    {% if redirect_field_value %}
    <input type="hidden" name="{{redirect_field_name}}" value="{{redirect_field_value}}" />
    {% endif %}

    {% bootstrap_form form %}

    {% buttons submit="Submit"  %}
    {% endbuttons %}

</form>

</div>

{% endblock %}

templates/event/organization_remove_manager.html
{% extends "core/base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load account %}

{% block content %}

<div class="container">

<h1 class="page-header">{% trans "Remove manager for" %} {{organization}}</h1>

<p>{% trans "Please confirm that you want to remove this user's manager permissions:" %} {% user_display removeuser %}</p>

<form class="form" method="post">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons submit="Submit"  %}
    {% endbuttons %}

</form>

</div>

{% endblock %}