lancms2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from event.views import EventListView, EventDetailView
from event.views import OrganizationDetailView, OrganizationCreateView

from core.views import UserDetailView

from event.views import organization_add_manager, organization_remove_manager

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'accounts/', include('allauth.urls')),
    url(r'accounts/profile/$', UserDetailView.as_view(), name='user_profile'),

    url(r'^$', EventListView.as_view(), name='event_list'),

    url(r'^o/(?P<slug>[\w-]+)/$', OrganizationDetailView.as_view(), name='org_detail'),
    url(r'^o/(?P<slug>[\w-]+)/addmanager/$', organization_add_manager, name='org_add_manager'),
    url(r'^o/(?P<slug>[\w-]+)/removemanager/(?P<user>\d+)/$', organization_remove_manager, name='org_remove_manager'),

    url(r'^e/(?P<slug>[\w-]+)/$', EventDetailView.as_view(), name='event_detail'),

    url(r'^a/org/create/$', OrganizationCreateView.as_view(), name='org_create'),
]

core/models.py
from django.db import models

event/models.py
from django.db import models

from simple_history.models import HistoricalRecords
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from guardian.models import UserObjectPermission
from django.contrib.contenttypes.models import ContentType

class ActiveOrganizationManager(models.Manager):
    def get_queryset(self):
        return super(ActiveOrganizationManager, self).get_queryset().filter(is_active=True)

class ActiveEventManager(models.Manager):
    def get_queryset(self):
        return super(ActiveEventManager, self).get_queryset().filter(is_active=True,organization__is_active=True)

class Organization(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField()

    is_active = models.BooleanField(default=True)

    history = HistoricalRecords()

    # order is important for Managers
    # default (used in CBVs ie. is the first Manager)
    # admin uses default, unless specified in ModelAdmin
    objects = ActiveOrganizationManager()
    objects_admin = models.Manager()


    def get_absolute_url(self):
        return reverse('org_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


    def get_managers(self):
        codename='manage_organization'
        type = ContentType.objects.get_for_model(self)
        return UserObjectPermission.objects.filter(permission__codename=codename, object_pk=self.pk, content_type=type)

    class Meta:
            permissions = (
                ('manage_organization', 'Can manage organization'),
            )



class Event(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField()

    is_active = models.BooleanField(default=True)

    start = models.DateTimeField()
    end = models.DateTimeField()

    venuename = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    postalcode = models.CharField(max_length=10)
    city = models.CharField(max_length=64)
    country = models.CharField(max_length=256)

    organization = models.ForeignKey(Organization)

    history = HistoricalRecords()

    # order is important for Managers
    # default (used in CBVs ie. is the first Manager)
    # admin uses default, unless specified in ModelAdmin
    objects = ActiveEventManager()
    objects_admin = models.Manager()

    def __str__(self):
        return self.name


    def get_managers(self):
        codename='manage_event'
        type = ContentType.objects.get_for_model(self)
        return UserObjectPermission.objects.filter(permission__codename=codename, object_pk=self.pk, content_type=type)


    class Meta:
            permissions = (
                ('manage_event', 'Can manage event'),
            )

core/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic.detail import DetailView

from django.contrib.auth.models import User


class UserDetailView(DetailView):
    model = User

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.pk)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserDetailView, self).dispatch(*args, **kwargs)

templates/core/base.html
{% extends "bootstrap3/bootstrap3.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}


{% block bootstrap3_content %}

<div class="container">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'event_list' %}">{{site_name|default:'lancms'}}</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if all_events %}
                    {% if all_events.count == 1 %}
                        <li><a href="{% url 'event_detail' slug=all_events.0.slug %}">{{all_events.0}}</a></li>
                    {% else %}
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Events" %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        {% for event in all_events %}
                        <li><a href="{% url 'event_detail' slug=event.slug %}">{{event.name}}</a></li>
                        {% endfor %}
                        </ul>
                    </li>
                    {% endif %}
                {% endif %}
                {% if all_organizations %}
                    {% if all_organizations.count == 1 %}
                        <li><a href="{% url 'org_detail' slug=all_organizations.0.slug %}">{{all_organizations.0}}</a></li>
                    {% else %}
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Organzations" %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        {% for org in all_organizations %}
                        <li><a href="{% url 'org_detail' slug=org.slug %}">{{org.name}}</a></li>
                        {% endfor %}
                        </ul>
                    </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_staff or request.user.is_superuser %}
                <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Admin" %}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><a href="{% url 'admin:index' %}">{% trans "Django Admin" %}</a></li>
                {% if perms.event.add_organization %}
                <li><a href="{% url 'org_create' %}">{% trans "Add organization" %}</a></li>
                {% endif %}
                </ul>
                </li>
                {% endif %}
                <li>
                {% if request.user.is_authenticated %}
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Signed in as"%} {{request.user}}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'user_profile' %}">{% trans "Show profile" %}</a></li>
                    <li><a href="{% url 'account_logout' %}">{% trans "Sign out" %}</a></li>
                </ul>
                {% else %}
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Not signed in" %}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'account_login' %}">{% trans "Sign in" %}</a></li>
                    <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
                </ul>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

{% bootstrap_messages %}

{% block content %}

{% endblock %}

</div> {# end container #}
{% endblock %}